server:
  port: 8181
spring:
    profiles:
        active: dev
    application:
        name: springboot-demo
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Hongkong
        username: root
        password: 123456
    jpa:
        show-sql: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          ddl-auto: update
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: Hongkong
